name: flutter_task_manager
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # intl - for date formater
#  intl: ^0.17.0
  flutter_keyboard_visibility: ^5.1.0
  get_it: ^7.2.0
  connectivity: ^3.0.6
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0
  flutter_hooks: ^0.18.0
  flutter_bloc: ^7.3.2
  auto_route: ^3.0.4
  equatable: ^2.0.3
  freezed_annotation: ^0.14.2
  easy_localization: ^3.0.0
#  dartz: ^0.10.0
  cupertino_icons: ^1.0.3
  mockito: ^5.0.16
  floor: ^1.2.0
  injectable: ^1.5.0
  rxdart: ^0.27.2
  dio: ^4.0.1
  retrofit: ^3.0.0

#
#  path_provider: ^2.0.1
#  provider: ^5.0.0
#  shared_preferences: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.2.0
  injectable_generator: ^1.5.2
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.4
  freezed: ^0.14.2
  retrofit_generator: ^3.0.0+1

flutter:
  uses-material-design: true
  assets:
   - lang/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
